# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f3a75355bf3e4cd791069a759795d99505434faef71018c807c7f4f83b7f965b8bfeeb3327024d14f98cbbed1cb6ee2f51d672708d62012bcd455cba05e20d

test:
  secret_key_base: c3c1371b795064940d084daa1587c9c64c8175d22b8881c89968595036a0bf121895136fe1e50424f084af497ccc7701f18c7ce6bb00660d9e7a4ce3777d0f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
